# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-08 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
